Fixing the prependExperiment method
getninjas/tagmanager-wrap pull request #7
Opened 2018-03-15 12:39 UTC by bernardosrulzon

PR irmão deste, no Scorpion: https://github.com/getninjas/getninjas/pull/3434

Me ajudem a rodar os testes e gerar o `dist`? Tks!

2018-03-15 17:41 UTC, iondrimba commented on dist/tagmanager-wrap.js
>      }, {
Esse é o dist, pode ignorar 👍

2018-03-15 17:41 UTC, iondrimba commented on index.html
> +  window.tagManagerDataLayer = [];
Código de demonstração

2018-03-15 17:42 UTC, iondrimba commented on karma.conf.js
> +        subdir: '/',
Exporting coverage results to root coverage folder for code climate integration

2018-03-15 17:43 UTC, iondrimba commented on spec/tagManagerWrap.spec.js
> +  window.tagManagerDataLayer = [];
Using googles `tagManagerDataLayer` global as reference

2018-03-15 17:44 UTC, iondrimba commented on src/tagmanager-wrap.js
> +    Object.assign(window.tagManagerDataLayer, this.dataLayer);
Merging local `dataLayer` ref with googles global `tagManagerDataLayer ` ref

2018-03-15 17:45 UTC, iondrimba commented on README.md
> +[![Build Status](https://semaphoreci.com/api/v1/iondrimba/tagmanager-wrap/branches/master/badge.svg)](https://semaphoreci.com/iondrimba/tagmanager-wrap)
Badges Semaphore, Code Climate

2018-03-16 12:24 UTC, williamcosta approved these changes

2018-03-16 12:41 UTC, iondrimba requested changes
There is some minor fixes to do 👍

2018-04-19 13:29 UTC, iondrimba commented on src/tagmanager-wrap.js
> +    iframe.style.display = 'none';
Changed this implementation to fix a Safaria 10 problem

2018-04-19 14:18 UTC, iondrimba commented on .drone.yml
> +pipeline:
Added build with drone CI, thanks @williamcosta 👍

2018-04-19 14:19 UTC, iondrimba commented on karma.conf.js
> +          '--no-sandbox',
Added this config to run Chrome inside drone CI

2018-04-19 14:39 UTC, felipeorlando commented on dist/tagmanager-wrap.js
> +        this.custom({ event: 'selfDescribingEvent', schema: 'iglu:br.com.getninjas/split_test/jsonschema/1-0-0', data: experiment });
The value for schema must be customizable.

2018-04-19 16:05 UTC, iondrimba commented on dist/tagmanager-wrap.js
> +        this.custom({ event: 'selfDescribingEvent', schema: 'iglu:br.com.getninjas/split_test/jsonschema/1-0-0', data: experiment });
Nice catch! I will try to make `{ event: 'selfDescribingEvent', schema: 'iglu:br.com.getninjas/split_test/jsonschema/1-0-0', data: experiment }` it as an option config

2018-04-19 16:30 UTC, felipeorlando approved these changes

2018-04-19 19:22 UTC, eduardojmatos commented on demo.js
> +      experimentDescription: 'PopUp/Modal quando o usuário deixa formulário',
Can we use EN text here?

2018-04-19 19:24 UTC, eduardojmatos approved these changes

2018-04-19 20:26 UTC, iondrimba commented on demo.js
> +      experimentDescription: 'PopUp/Modal quando o usuário deixa formulário',
Sure!

2018-04-19 20:41 UTC, iondrimba approved these changes

2018-04-19 20:42 UTC, iondrimba commented on demo.js
> +      experimentDescription: 'PopUp/Modal quando o usuário deixa formulário',
DONE! @eduardojmatos  👍

2018-04-20 12:48 UTC, williamcosta approved these changes

2018-04-20 12:57 UTC, merged